# Generated by Django 5.2.5 on 2025-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpls_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, help_text='Nome original do cliente', max_length=300)),
                ('customer_name_normalized', models.CharField(db_index=True, help_text='Nome normalizado (lowercase, sem acentos)', max_length=300)),
                ('customer_name_clean', models.CharField(db_index=True, help_text='Nome limpo para busca (só alfanumérico)', max_length=300)),
                ('vpn_ids', models.JSONField(default=list, help_text='Lista de VPN IDs onde este cliente aparece')),
                ('equipment_names', models.JSONField(default=list, help_text='Lista de nomes de equipamentos')),
                ('interfaces_data', models.JSONField(default=dict, help_text='Mapeamento equipamento -> interfaces')),
                ('descriptions', models.JSONField(default=list, help_text='Todas as descrições onde cliente aparece')),
                ('contexts', models.JSONField(default=list, help_text='Contextos: LAG descriptions, group names, etc.')),
                ('total_occurrences', models.IntegerField(default=0, help_text='Total de vezes que cliente aparece')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_files', models.JSONField(default=list, help_text='Arquivos JSON onde foi encontrado')),
            ],
            options={
                'db_table': 'mpls_analyzer_customer_index',
                'ordering': ['-total_occurrences', 'customer_name_normalized'],
                'indexes': [models.Index(fields=['customer_name_normalized'], name='mpls_analyz_custome_8db3b9_idx'), models.Index(fields=['customer_name_clean'], name='mpls_analyz_custome_4a3013_idx'), models.Index(fields=['customer_name'], name='mpls_analyz_custome_c52e30_idx'), models.Index(fields=['total_occurrences'], name='mpls_analyz_total_o_0d7591_idx'), models.Index(fields=['last_updated'], name='mpls_analyz_last_up_72648f_idx')],
            },
        ),
    ]
