# Generated by Django 5.2.5 on 2025-08-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_microservice_loadbalancerconfig_circuitbreaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceendpoint',
            name='rate_limit',
            field=models.IntegerField(default=10000),
        ),
    ]
